mkdir Ingeniería_Civil
mkdir Ingeniería_Civil/Semestre_1
mkdir Ingeniería_Civil/Semestre_2
mkdir Ingeniería_Civil/Semestre_3
mkdir Ingeniería_Civil/Semestre_4
mkdir Ingeniería_Civil/Semestre_5
mkdir Ingeniería_Civil/Semestre_6
mkdir Ingeniería_Civil/Semestre_7
mkdir Ingeniería_Civil/Semestre_8
mkdir Ingeniería_Civil/Semestre_9
mkdir Ingeniería_Civil/Semestre_10

mkdir Ingeniería_Civil/Semestre_1/01_Álgebra
mkdir Ingeniería_Civil/Semestre_1/02_Cálculo_I
mkdir Ingeniería_Civil/Semestre_1/03_Dibujo_para_Ingeniería
mkdir Ingeniería_Civil/Semestre_1/04_Física_I
mkdir Ingeniería_Civil/Semestre_1/05_Química_General

mkdir Ingeniería_Civil/Semestre_2/06_Álgebra_Lineal_y_Teoría_Matricial
mkdir Ingeniería_Civil/Semestre_2/07_Cálculo_II
mkdir Ingeniería_Civil/Semestre_2/08_Estadística_I
mkdir Ingeniería_Civil/Semestre_2/09_Física_II
mkdir Ingeniería_Civil/Semestre_2/10_Programación_I

mkdir Ingeniería_Civil/Semestre_3/11_Ecuaciones_Diferenciales
mkdir Ingeniería_Civil/Semestre_3/12_Geometría_Descriptiva
mkdir Ingeniería_Civil/Semestre_3/13_Estabilidad_y_Tipología_Estructuras
mkdir Ingeniería_Civil/Semestre_3/14_Hidráulica_I
mkdir Ingeniería_Civil/Semestre_3/15_Metodología_de_la_Investigación
mkdir Ingeniería_Civil/Semestre_3/16_Sistemas_de_Información_Geográfica
mkdir Ingeniería_Civil/Semestre_3/17_Topografía

mkdir Ingeniería_Civil/Semestre_4/18_Geología
mkdir Ingeniería_Civil/Semestre_4/19_Estructuras_Isostáticas
mkdir Ingeniería_Civil/Semestre_4/20_Hidráulica_II
mkdir Ingeniería_Civil/Semestre_4/21_Hidrología
mkdir Ingeniería_Civil/Semestre_4/22_Materiales_de_Construcción
mkdir Ingeniería_Civil/Semestre_4/23_Métodos_Numéricos
mkdir Ingeniería_Civil/Semestre_4/24_Electrotecnia

mkdir Ingeniería_Civil/Semestre_5/25_Ingeniería_Sanitaria_I
mkdir Ingeniería_Civil/Semestre_5/26_Resistencia_de_Materiales
mkdir Ingeniería_Civil/Semestre_5/27_Mecánica_de_Suelos_I
mkdir Ingeniería_Civil/Semestre_5/28_Estructuras_Hiperestáticas
mkdir Ingeniería_Civil/Semestre_5/29_Medio_Ambiente
mkdir Ingeniería_Civil/Semestre_5/30_Obras_Hidráulicas_I

mkdir Ingeniería_Civil/Semestre_6/31_Estructuras_de_Hormigón_Armado_I
mkdir Ingeniería_Civil/Semestre_6/32_Ingeniería_Sanitaria_II
mkdir Ingeniería_Civil/Semestre_6/33_Mecánica_de_Suelos_II
mkdir Ingeniería_Civil/Semestre_6/34_Obras_Hidráulicas_II
mkdir Ingeniería_Civil/Semestre_6/35_Economía_para_la_Ingeniería
mkdir Ingeniería_Civil/Semestre_6/36_Análisis_Matricial_de_Estructuras
mkdir Ingeniería_Civil/Semestre_6/37_Ingeniería_de_Tráfico_y_Vialidad

mkdir Ingeniería_Civil/Semestre_7/38_Estructuras_de_Madera
mkdir Ingeniería_Civil/Semestre_7/39_Plantas_de_Tratamiento
mkdir Ingeniería_Civil/Semestre_7/40_Carreteras
mkdir Ingeniería_Civil/Semestre_7/41_Estructuras_de_Hormigón_Armado_II
mkdir Ingeniería_Civil/Semestre_7/42_Construcción_de_Viviendas_y_Edificios
mkdir Ingeniería_Civil/Semestre_7/43_Legislación_para_la_Ingeniería
mkdir Ingeniería_Civil/Semestre_7/44_Instalaciones_Domiciliarias_e_Industriales

mkdir Ingeniería_Civil/Semestre_8/45_Maquinaria_y_Equipo
mkdir Ingeniería_Civil/Semestre_8/46_Estructuras_Metálicas
mkdir Ingeniería_Civil/Semestre_8/47_Preparación_y_Evaluación_de_Proyectos
mkdir Ingeniería_Civil/Semestre_8/48_Estructuras_de_Hormigón_Preesforzado
mkdir Ingeniería_Civil/Semestre_8/49_Fundaciones
mkdir Ingeniería_Civil/Semestre_8/50_Pavimentos

mkdir Ingeniería_Civil/Semestre_9/51_Trabajo_de_Grado_I
mkdir Ingeniería_Civil/Semestre_9/52_Puentes
mkdir Ingeniería_Civil/Semestre_9/53_Vías_de_Transporte_Aeropuertos_y_Vías_Férreas
mkdir Ingeniería_Civil/Semestre_9/54_Presupuestos_Cronogramas_Administración_Dirección_y_Fiscalización_de_Obras

mkdir Ingeniería_Civil/Semestre_10/55_Trabajo_de_Grado_II
