mkdir ING_Comercial
mkdir ING_Comercial/Semestre_1
mkdir ING_Comercial/Semestre_2
mkdir ING_Comercial/Semestre_3
mkdir ING_Comercial/Semestre_4
mkdir ING_Comercial/Semestre_5
mkdir ING_Comercial/Semestre_6
mkdir ING_Comercial/Semestre_7
mkdir ING_Comercial/Semestre_8
mkdir ING_Comercial/Semestre_9
mkdir ING_Comercial/Semestre_10

mkdir ING_Comercial/Semestre_1/01_Administración
mkdir ING_Comercial/Semestre_1/02Álgebra
mkdir ING_Comercial/Semestre_1/03_Contabilidad_Básica
mkdir ING_Comercial/Semestre_1/04_Cálculo_I
mkdir ING_Comercial/Semestre_1/05_Economía

mkdir ING_Comercial/Semestre_2/06Álgebra_Lineal_y_Teoría_Matricial
mkdir ING_Comercial/Semestre_2/07_Cálculo_II
mkdir ING_Comercial/Semestre_2/08_Contabilidad_Intermedia
mkdir ING_Comercial/Semestre_2/09_Estadística_I
mkdir ING_Comercial/Semestre_2/10_Microeconomía_I

mkdir ING_Comercial/Semestre_3/11_Administración_del_Talento_Humano
mkdir ING_Comercial/Semestre_3/12_Contabilidad_de_Costos
mkdir ING_Comercial/Semestre_3/13_Ecuaciones_Diferenciales
mkdir ING_Comercial/Semestre_3/14_Estadística_II
mkdir ING_Comercial/Semestre_3/15_Metodología_de_la_Investigación
mkdir ING_Comercial/Semestre_3/16_Microeconomía_II

mkdir ING_Comercial/Semestre_4/17_Investigación_Operativa_I
mkdir ING_Comercial/Semestre_4/18_Macroeconomía_I
mkdir ING_Comercial/Semestre_4/19_Marketing_Estratégico_I
mkdir ING_Comercial/Semestre_4/20_Matemáticas_Financieras
mkdir ING_Comercial/Semestre_4/21_Métodos_Numéricos
mkdir ING_Comercial/Semestre_4/22_Presupuestos_y_Control

mkdir ING_Comercial/Semestre_5/23_Econometría_I
mkdir ING_Comercial/Semestre_5/24_Finanzas_I
mkdir ING_Comercial/Semestre_5/25_Investigación_de_Mercados
mkdir ING_Comercial/Semestre_5/26_Investigación_Operativa_II
mkdir ING_Comercial/Semestre_5/27_Macroeconomía_II
mkdir ING_Comercial/Semestre_5/28_Marketing_Estratégico_II

mkdir ING_Comercial/Semestre_6/29_Econometría_II
mkdir ING_Comercial/Semestre_6/30_Economía_Empresarial
mkdir ING_Comercial/Semestre_6/31_Finanzas_II
mkdir ING_Comercial/Semestre_6/32_Legislación_para_Ingeniería
mkdir ING_Comercial/Semestre_6/33_Marketing_de_Servicios
mkdir ING_Comercial/Semestre_6/34_Organización_Industrial

mkdir ING_Comercial/Semestre_7/35_Administración_de_Ventas
mkdir ING_Comercial/Semestre_7/36_Administración_de_la_Producción
mkdir ING_Comercial/Semestre_7/37_Administración_Pública
mkdir ING_Comercial/Semestre_7/38_Análisis_Cuantitativo_Decisional
mkdir ING_Comercial/Semestre_7/39_Comercio_Exterior_e_Internacional
mkdir ING_Comercial/Semestre_7/40_Mercados_e_Instituciones_Financieras

mkdir ING_Comercial/Semestre_8/41_Administración_Logística
mkdir ING_Comercial/Semestre_8/42_Economía_Monetaria_y_Fiscal
mkdir ING_Comercial/Semestre_8/43_Emprendurismo
mkdir ING_Comercial/Semestre_8/44_Habilidades_Personales_y_Directivas
mkdir ING_Comercial/Semestre_8/45_Modelado_y_Simulación
mkdir ING_Comercial/Semestre_8/46_Preparación_y_Evaluación_de_Proyectos

mkdir ING_Comercial/Semestre_9/47_Administración_de_Proyectos
mkdir ING_Comercial/Semestre_9/48_Juego_de_Negocios
mkdir ING_Comercial/Semestre_9/49_Planificación_Estratégica_de_Marketing
mkdir ING_Comercial/Semestre_9/50_Trabajo_de_Grado_I

mkdir ING_Comercial/Semestre_10/51_Trabajo_de_Grado_II
mkdir ING_Comercial/Semestre_10/52_Tópicos_de_Marketing
mkdir ING_Comercial/Semestre_10/53_Valores_y_Seguros
