mkdir Ingeniería_de_Sistemas
mkdir Ingeniería_de_Sistemas/Semestre_1
mkdir Ingeniería_de_Sistemas/Semestre_2
mkdir Ingeniería_de_Sistemas/Semestre_3
mkdir Ingeniería_de_Sistemas/Semestre_4
mkdir Ingeniería_de_Sistemas/Semestre_5
mkdir Ingeniería_de_Sistemas/Semestre_6
mkdir Ingeniería_de_Sistemas/Semestre_7
mkdir Ingeniería_de_Sistemas/Semestre_8
mkdir Ingeniería_de_Sistemas/Semestre_9
mkdir Ingeniería_de_Sistemas/Semestre_10

mkdir Ingeniería_de_Sistemas/Semestre_1/01_Álgebra
mkdir Ingeniería_de_Sistemas/Semestre_1/02_Cálculo_I
mkdir Ingeniería_de_Sistemas/Semestre_1/03_Dibujo_para_Ingeniería
mkdir Ingeniería_de_Sistemas/Semestre_1/04_Física_I
mkdir Ingeniería_de_Sistemas/Semestre_1/05_Química_General

mkdir Ingeniería_de_Sistemas/Semestre_2/06_Álgebra_Lineal_y_Teoría_Matricial
mkdir Ingeniería_de_Sistemas/Semestre_2/07_Programación
mkdir Ingeniería_de_Sistemas/Semestre_2/08_Cálculo_II
mkdir Ingeniería_de_Sistemas/Semestre_2/09_Estadística_I
mkdir Ingeniería_de_Sistemas/Semestre_2/10_Física_II

mkdir Ingeniería_de_Sistemas/Semestre_3/11_Ecuaciones_Diferenciales
mkdir Ingeniería_de_Sistemas/Semestre_3/12_Análisis_y_Diseño_de_Sistemas_Basados_en_Microprocesadores
mkdir Ingeniería_de_Sistemas/Semestre_3/13_Estadística_II
mkdir Ingeniería_de_Sistemas/Semestre_3/14_Variable_Compleja
mkdir Ingeniería_de_Sistemas/Semestre_3/15_Estructura_de_Datos_I
mkdir Ingeniería_de_Sistemas/Semestre_3/16_Metodología_de_la_Investigación
mkdir Ingeniería_de_Sistemas/Semestre_3/17_Programación_II

mkdir Ingeniería_de_Sistemas/Semestre_4/18_Métodos_Numéricos
mkdir Ingeniería_de_Sistemas/Semestre_4/19_Economía_para_Ingeniería
mkdir Ingeniería_de_Sistemas/Semestre_4/20_Investigación_Operativa_I
mkdir Ingeniería_de_Sistemas/Semestre_4/21_Programación_Avanzada
mkdir Ingeniería_de_Sistemas/Semestre_4/22_Base_de_Datos_I
mkdir Ingeniería_de_Sistemas/Semestre_4/23_Estructura_de_Datos_II
mkdir Ingeniería_de_Sistemas/Semestre_4/24_Ingeniería_de_Sistemas

mkdir Ingeniería_de_Sistemas/Semestre_5/25_Análisis_y_Diseño_de_Sistemas_I
mkdir Ingeniería_de_Sistemas/Semestre_5/26_Redes_de_Computadoras_I
mkdir Ingeniería_de_Sistemas/Semestre_5/27_Base_de_Datos_II
mkdir Ingeniería_de_Sistemas/Semestre_5/28_Inteligencia_Artificial_I
mkdir Ingeniería_de_Sistemas/Semestre_5/29_Taller_de_Programación
mkdir Ingeniería_de_Sistemas/Semestre_5/30_Investigación_Operativa_II

mkdir Ingeniería_de_Sistemas/Semestre_6/31_Análisis_y_Diseño_de_Sistemas_II
mkdir Ingeniería_de_Sistemas/Semestre_6/32_Inteligencia_Artificial_II
mkdir Ingeniería_de_Sistemas/Semestre_6/33_Redes_de_Computadoras_II
mkdir Ingeniería_de_Sistemas/Semestre_6/34_Base_de_Datos_III
mkdir Ingeniería_de_Sistemas/Semestre_6/35_Administración_de_Sistemas_Operativos_y_Servidores
mkdir Ingeniería_de_Sistemas/Semestre_6/36_Internet_de_las_Cosas

mkdir Ingeniería_de_Sistemas/Semestre_7/37_Ingeniería_de_Software_I
mkdir Ingeniería_de_Sistemas/Semestre_7/38_Seguridad_de_Sistemas
mkdir Ingeniería_de_Sistemas/Semestre_7/39_Redes_de_Computadoras_III
mkdir Ingeniería_de_Sistemas/Semestre_7/40_Legislación_para_Ingeniería
mkdir Ingeniería_de_Sistemas/Semestre_7/41_Modelación_y_Simulación_de_Sistemas
mkdir Ingeniería_de_Sistemas/Semestre_7/42_Diseño_Organizacional

mkdir Ingeniería_de_Sistemas/Semestre_8/43_Ingeniería_de_Software_II
mkdir Ingeniería_de_Sistemas/Semestre_8/44_Informática_Forense
mkdir Ingeniería_de_Sistemas/Semestre_8/45_Preparación_y_Evaluación_de_Proyectos
mkdir Ingeniería_de_Sistemas/Semestre_8/46_Práctica_Empresarial
mkdir Ingeniería_de_Sistemas/Semestre_8/47_Reingeniería_de_Sistemas
mkdir Ingeniería_de_Sistemas/Semestre_8/48_Robótica

mkdir Ingeniería_de_Sistemas/Semestre_9/49_Trabajo_de_Grado_I
mkdir Ingeniería_de_Sistemas/Semestre_9/50_Taller_de_TICS_y_Software
mkdir Ingeniería_de_Sistemas/Semestre_9/51_Auditorías_Sistemas

mkdir Ingeniería_de_Sistemas/Semestre_10/52_Administración_y_Dirección_de_Operaciones
mkdir Ingeniería_de_Sistemas/Semestre_10/53_Trabajo_de_Grado_II
mkdir Ingeniería_de_Sistemas/Semestre_10/54_Taller_de_Modelación_y_Simulación
